### ISSUE TITLE
Limited vision with Perfect Vision is not a circle for those without Dim Vision

### ISSUE THREAD

**Issue by Zamrod** [manuelVo/foundryvtt-lichtgeschwindigkeit#13] opened 2021-06-28 15:42 UTC
Steps to recreate:
Have both lichtgeschwindigkeit and Perfect Vision installed
Go into the scene settings and turn on limited vision to something like 30 and Unrestricted Vision Range
Select a token that has vision enabled but 0 Dim Vision and 0 Bright Vision
The vision isn't limited in a circle around the token but what appears to be a Parallelogram that changes dimensions as you move the token around the scene.
![vision](https://user-images.githubusercontent.com/12570777/123664819-52c0d900-d7fd-11eb-83d3-0004791e5eb6.png)

**Comment by manuelVo** [comment] 2021-06-28 19:14
I'm unable to reproduce this. Do you have other modules enabled in your world?

**Comment by Zamrod** [comment] 2021-06-28 19:15
That screenshot was just libWrapper, Lichtgeschwindigkeit, and Perfect Vision

**Comment by manuelVo** [comment] 2021-06-28 19:18
Can you send me the world in which this bug is happening? Maybe that'll help me with reproducing it locally.

**Comment by Zamrod** [comment] 2021-06-28 19:23
I don't even think it is the world. I think when I create other scenes even in that world, I'm not seeing the issue. Here is an export of the scene json 
[fvtt-Scene-pt2-primordial-crevasse-(alt).txt](https://github.com/manuelVo/foundryvtt-lichtgeschwindigkeit/files/6728777/fvtt-Scene-pt2-primordial-crevasse-.alt.txt)
renamed as a .txt

**Comment by Zamrod** [comment] 2021-06-28 19:32
Actually, I think I figured out what causes it. I have walls around the outside edge of the scene. When I add those walls into another scene the same thing happens.

**Comment by manuelVo** [comment] 2021-06-28 19:39
That does the trick. I can reproduce it now as well.

**Comment by dev7355608** [comment] 2021-06-30 12:00
This wasn't Lichtgeschwindigkeit's fault. Fixed in PV 1.9.12.

**Comment by manuelVo** [comment] 2021-07-01 09:41
Fixed in https://github.com/dev7355608/perfect-vision/commit/c86a51a788c949797144423e97b0db88eab691ba

**Closed as completed by manuelVo** 2021-07-01 09:41 UTC
Labels: module conflict
